import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function NewsPage() {

  const router = useRouter();

  return (
    <div>
      <Head>
        <title>News page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>News page</h1>

        <ul>
          <li>
            <Link href="/news/nextjs-is-great">NextJS is great</Link>
          </li>
          <li>
            <a href="/news/something-else">Something else</a>
          </li>
        </ul>


        <br />
        <br />
        <br />

        <button onClick={() => router.push('/news/navegação via código')}>
          Navegação via código
        </button>


        <br />
        <br />
        <br />

      </main>

      <footer>
        <a
          href="https://github.com/rafaelguinho"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Guinho
        </a>
      </footer>
    </div>
  );
}
